name: Bug Report
description: Report bugs related to this project.
labels: [Bug]

body:          
  - type: textarea
    attributes:
        label: Info
        description: Anything that can help me identify the device and software version that you are using.
        value: |
          - Your device: 
          - Your macOS version: 
          - Microsoft Office version:
    validations:
        required: true

  - type: textarea
    attributes:
        label: Expected Behavior
        description: Tell me what should happen.
    validations:
        required: true

  - type: textarea
    attributes:
        label: Current Behavior
        description: Tell me what happens when you've seen.
    validations:
        required: true

  - type: textarea
    attributes:
        label: Possible Solution
        description: Suggest a fix or reason for the bug (optional).

  - type: textarea
    attributes:
        label: Steps to Reproduce
        description: Provide a link to a live example, or an unambiguous set of steps to reproduce this bug.\n(Include code to reproduce, if you can.)
        value: |
          1. 
          2. 
          3. 
    validations:
        required: true

  - type: textarea
    attributes:
        label: Additional context
        description: Add any other context about the problem here.

  - type: checkboxes
    attributes:
       label: Acknowledgements
       description: Before submitting this issue, please check again. Your issue may be **CLOSED AS UNPLANNED** if you don't follow the checklist below! 
       options:
          - label: I agree that this issue is solely related to this project.
            required: true
          - label: I agree that this issue is not a feature request, nor a duplicate of an existing issue.
            required: true
          - label: I've chosen an appropriate title for this issue and all requested information has been provided correctly.
            required: true
