name: Feature Request
description: Feature request on this project.
labels: [Feature Request]

body:          
  - type: textarea
    attributes:
        label: Feature Request
        description: Provide the feature that you would like to request on this project.
    validations:
        required: true

  - type: checkboxes
    attributes:
       label: Acknowledgements
       description: Before submitting this issue, please check again. Your issue may be **CLOSED AS UNPLANNED** if you don't follow the checklist below! 
       options:
          - label: I agree that this issue is solely related to this project.
            required: true
          - label: I agree that this issue is not a bug report, nor a duplicate of an existing issue.
            required: true
          - label: I've chosen an appropriate title for this issue and all requested information has been provided correctly.
            required: true
